---
root: true
env:
  browser: true
  node: true
extends: 'standard'
# add your custom rules here
rules:
  space-before-function-paren:
    - 'error'
    - anonymous: 'always'
      named: 'ignore'
      asyncArrow: 'always'
