---
language: node_js
node_js:
  - 'lts/*'
env:
  secure: dM59kLfCJyhynU/GdMW0w/d4gvigaXb/oQLjOwoUx41otwaIV8D35Yjm1TqN+aa4KmCe5u8ARkbjsHKyjeP/iJrtdoqea+Oaz5WwNc+kTB5YW/nz+1oSBPdjYyQSgWJovSEWhu6vFo7WD9GUGElJNVQ3/VpTxZtd9qWgNJjjY9GmobZi7joBN3mEXbuRlSZ9tr8NNrBT1Qx7Dh4/KxhRDcmfqMMv2Sc23eLo2VCQyy5adYWWxz8Zrn70nenTBejGm5quW/iy8i0QRleXMrXGqwv6yOvudq3gGqVtjm8R7yzWzVvLQOprqjmB4ffK+ZYgij/skvJvVrUdK6MtHsx5cRyH/3+hNElLj8RItEwzsEfoJwaS7ekDeefzT+M67FgB1Ux6tueGR1CenSDAPjpkQZZDuLluUypc5NrfOoIdETnErVKvy/mCoxf5nf4knDDp13Es9QSCHPeza+ZyUDPgR9hx2OEMC84nkCGNWFff8FbGp3CqvPOd8/YMqoUUqgvOk90oxbgoVZCoaobQA+QYvMzb/r+/t0Zp3Xcr6yzxSzLqZheHwL2XMsxcE01LsnvANGcvFcyvBsolr183JF9HVuYce/5Nj2D/ReqvEc9vLtGHM8B2y7Iey2QIJQunu0ggXbuU3CXE/v6KZ7PzAs5pEm3adNQrJQ6SIok6RrmvCy4=
before_install:
  - sudo apt-get install -y git-core libnss-mdns libavahi-compat-libdnssd-dev
script:
  - yarn lint
  - yarn test
notifications:
  email: false
  slack:
    secure: vOp/QmcJp7Gq5I1Udf9Ut10E32ij9a12b2xaWGxfoE1k5Q4VWvovt4FXQr9KMaOr2b/bFVyLod9fx4GHVyLLxs8Oyl0VxiHmX9mABBnZGdVg8XwlfC4d0JoIZ+t4XaOPjWn/OO23NECCCud/S9TDLmZBbX+z1uVxx0AzdCmqsI+q3Non9S2ykP6vOb5I2UKIaEQNZ8R+zlNkrEEXILb+5k8yVYKHmx9h1Ft7FzeOU9fSyX772oCvF/YCk5VrgIlw5gWkQ3wIuIBk+LdOPQsoZShK1stoX8L6s5kw2mcVx1SxuHO/KqQLTZrQg/4TMjeEufgRhceIaq8rhmKdStFOcCNmydnaQn0LUhNcK9FVH+QXykUe1f6m6ly58dY3+JaH7nUyE+PZ9p4VQqshQ/pvlsZKUgmd5syxVTDeTunSR8USEItkVDauyMFW15oqdsnyVgrPAz1Eqa2wj2KdMalpmpxryHjIAqwhrhNcKpDzzItfYCnHDIzb7uOif78gQh9dMxN0OprwPtVuWouLilpBrfBrHYiyx6flSnZpLGMQfS7ho6tDQ+k9lNnDlF4onAhGRED0wNiUMOywjG0kgm5a8yQaXLYmgisHs1UBQtVGWbrUTDRpD6bBZWUSOqjo21D3MJ1nMsaWPAxw2odLtwNO785On3txatjeZwjLgsJ4rd4=
