---
language: node_js
node_js:
  - 'node'
script:
  - yarn lint
  - yarn test
notifications:
  email: false
  slack:
    secure: vOp/QmcJp7Gq5I1Udf9Ut10E32ij9a12b2xaWGxfoE1k5Q4VWvovt4FXQr9KMaOr2b/bFVyLod9fx4GHVyLLxs8Oyl0VxiHmX9mABBnZGdVg8XwlfC4d0JoIZ+t4XaOPjWn/OO23NECCCud/S9TDLmZBbX+z1uVxx0AzdCmqsI+q3Non9S2ykP6vOb5I2UKIaEQNZ8R+zlNkrEEXILb+5k8yVYKHmx9h1Ft7FzeOU9fSyX772oCvF/YCk5VrgIlw5gWkQ3wIuIBk+LdOPQsoZShK1stoX8L6s5kw2mcVx1SxuHO/KqQLTZrQg/4TMjeEufgRhceIaq8rhmKdStFOcCNmydnaQn0LUhNcK9FVH+QXykUe1f6m6ly58dY3+JaH7nUyE+PZ9p4VQqshQ/pvlsZKUgmd5syxVTDeTunSR8USEItkVDauyMFW15oqdsnyVgrPAz1Eqa2wj2KdMalpmpxryHjIAqwhrhNcKpDzzItfYCnHDIzb7uOif78gQh9dMxN0OprwPtVuWouLilpBrfBrHYiyx6flSnZpLGMQfS7ho6tDQ+k9lNnDlF4onAhGRED0wNiUMOywjG0kgm5a8yQaXLYmgisHs1UBQtVGWbrUTDRpD6bBZWUSOqjo21D3MJ1nMsaWPAxw2odLtwNO785On3txatjeZwjLgsJ4rd4=
