googlehome:
  ip: 'TODO your google home ip'
  language: 'ja'
pokeapi:
  language: 'ja'
  flavorText:
    language: 'ja'
    version: 'omega-ruby'
beebotte:
  channel: 'your channel'
  resource: 'your resource'
  token: 'your token'
